[connections.course_assistant]
    type="sql"
    dialect="postgresql"
    username="postgres"
    password="postgres"
    host="localhost" # IP or URL
    port=5433 # Port number
    database="course_assistant" # Database name